FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY SandwichMaker/SandwichMaker.csproj SandwichMaker/
COPY RabbitQueue/RabbitQueue.csproj RabbitQueue/
RUN dotnet restore SandwichMaker/SandwichMaker.csproj
COPY . .
WORKDIR /src/SandwichMaker
RUN dotnet build SandwichMaker.csproj -c Release -o /app -r linux-arm

FROM build AS publish
RUN dotnet publish SandwichMaker.csproj -c Release -o /app -r linux-arm

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "SandwichMaker.dll"]
